import { db } from "../../../../firebase/clientApp";
import { collection, getDocs } from "firebase/firestore";
import RegisteredPeople from "../../../../components/registerdpeople";
import { currentUser } from "@clerk/nextjs/server";

export const metadata = {
  title: "Registered Participants",
  description: "Generated by create next app",
};

export default async function Registered_People() {
  const user = await currentUser();
  const isAdmin = user?.publicMetadata?.role === "admin";
try{
  if (isAdmin) {
    const RegisterRef = collection(db, "Registered-Events");
  const querySnapShot = await getDocs(RegisterRef);
  const RegistrationData = querySnapShot.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
  }));

  const data = JSON.parse(JSON.stringify(RegistrationData));

  if (!data.length) {
    throw new Error("Training Data Not Found");
  }

  return <RegisteredPeople data={data} />;
  }
}
catch(error){
  console.error("Your not authenticated to access this page")
}
  

  
}
