import "./globals.css";

import LandingHeader from "./components/landingheader";

export const metadata = {
  title: "Event Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LandingHeader />
        {children}
      </body>
    </html>
  );
}
